"""Benchmark reports (spec benchmark-reporting; REP-01 to REP-07; tasks 5.1 to 5.5).

A report is generated by deterministic code from **stored** run results (a
:class:`~finplan_model.reporting.benchmark.BenchmarkRun` or its ``to_dict()``), and has:

* ``sections`` - kept separate and never blended into one score (REP-01):

  - ``portfolio_performance`` - per strategy and per evaluation period: net and gross cumulative
    return, annualized volatility, Sharpe ratio (with its stated risk-free source), maximum
    drawdown, turnover and transaction costs (total plus fee, spread and slippage components), all
    computed by the common evaluator. Rows are grouped by period type, in separately labeled
    columns: ``walk_forward_fold`` (one row per fold plus the ``aggregate`` of the folds),
    ``validation``, ``holdout`` and ``prospective_paper`` (REP-02, REP-04);
  - ``model_accuracy`` - only for strategies that make predictions; ``not_applicable`` otherwise;
  - ``training_rewards`` - only for learned strategies; ``not_applicable`` otherwise;
  - ``compute_cost`` - per run: instance type and count, billed runtime seconds, the pre-flight
    estimate labeled ``estimated`` and, when billing data exists, the actual cost labeled
    ``actual`` (else ``pending``) (REP-03);

* ``variability`` - for strategies with randomness: number of seeds and mean, min, max and range of
  every portfolio metric per period (REP-05);
* ``holdout`` - bounds, the attached holdout access log (and whether the holdout was reused), and
  the holdout metrics records whose values are the holdout column's numbers (REP-07);
* ``synthetic`` labels on the report and every row.

``report_checksum`` is the SHA-256 of the canonical JSON of ``content``; regenerating from the same
stored results gives the same content and checksum (REP-06). Narrative text is kept outside
``content`` (``narrative``) and is not part of the checksum.

Aggregate of walk-forward folds (stitched out-of-sample): fold test windows are disjoint and
consecutive; session returns of the folds are concatenated (each fold starts from the initial
cash). Cumulative returns compound the fold returns; volatility and Sharpe use the concatenated
session returns; maximum drawdown uses the chained value path; turnover and costs are sums over
folds.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from finplan_model.core.artifacts import ArtifactRef, ArtifactStore, canonical_json_bytes, sha256_checksum
from finplan_model.core.errors import FinplanError
from finplan_model.core.ids import require_id
from finplan_model.sim import metrics as m

from .benchmark import BenchmarkRun, ResultEntry
from .storage import assert_aggregate_only, require_research_storage

__all__ = [
    "BenchmarkReport",
    "PERIOD_TYPES",
    "PORTFOLIO_METRICS",
    "ReportConfig",
    "aggregate_fold_metrics",
    "build_report",
    "report_from_stored",
    "store_report",
    "to_run_result_payload",
]

REPORT_VERSION = "benchmark-report-v1"
REPORT_KIND = "benchmark_report"
NARRATIVE_KIND = "report_narrative"
PERIOD_TYPES = ("walk_forward_fold", "validation", "holdout", "prospective_paper")
PORTFOLIO_METRICS = (
    "net_cumulative_return",
    "gross_cumulative_return",
    "annualized_volatility",
    "sharpe_ratio",
    "max_drawdown",
    "turnover",
    "total_transaction_costs",
    "total_fees",
    "total_spread_cost",
    "total_slippage_cost",
)
SECTIONS = ("portfolio_performance", "model_accuracy", "training_rewards", "compute_cost")
_BLEND_WORDS = ("blend", "combined", "composite", "overall_score", "single_score", "weighted_score", "score_weights", "total_score")


@dataclass(frozen=True)
class ReportConfig:
    title: str = "benchmark"
    include_seed_rows: bool = True

    @classmethod
    def from_dict(cls, d: Mapping[str, Any] | None) -> "ReportConfig":
        d = dict(d or {})
        for k in d:
            if any(w in k.lower() for w in _BLEND_WORDS) or k.lower() == "score":
                raise FinplanError.validation("reports never blend portfolio performance, model accuracy, training rewards and compute cost into one score", pointer=f"/{k}", reason="blended_score_refused")
            if k not in ("title", "include_seed_rows", "$comment"):
                raise FinplanError.validation(f"unknown report setting {k}", pointer=f"/{k}")
        title = d.get("title", "benchmark")
        if not isinstance(title, str) or not (0 < len(title) <= 120):
            raise FinplanError.validation("title must be a short string", pointer="/title")
        isr = d.get("include_seed_rows", True)
        if not isinstance(isr, bool):
            raise FinplanError.validation("include_seed_rows must be a boolean", pointer="/include_seed_rows")
        return cls(title, isr)


@dataclass(frozen=True)
class BenchmarkReport:
    content: dict[str, Any]
    report_checksum: str
    narrative: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        """The numeric evidence and its checksum; narrative is stored separately."""
        return {"content": self.content, "report_checksum": self.report_checksum}

    @property
    def synthetic(self) -> bool:
        return bool(self.content["synthetic"])


# ===================================================================== metrics
def _portfolio(metrics_doc: Mapping[str, Any]) -> dict[str, Any]:
    return {k: metrics_doc.get(k) for k in PORTFOLIO_METRICS}


def aggregate_fold_metrics(results: Sequence[Mapping[str, Any]], *, periods_per_year: int = 252, cash_rate_annual: float = 0.0) -> dict[str, Any]:
    """Stitched out-of-sample metrics of fold results (``EvaluationResult.to_dict()``), in fold order."""
    if not results:
        raise FinplanError.validation("no fold results to aggregate", pointer="/entries")
    session_rets: list[float] = []
    net_growth = gross_growth = 1.0
    chained = [1.0]
    sums = {k: 0.0 for k in ("turnover", "total_transaction_costs", "total_fees", "total_spread_cost", "total_slippage_cost")}
    for r in results:
        init = float(r["identity"]["settings"]["initial_cash"])
        nav = [row["value"] for row in r["simulation"]["nav"]]
        gross = [row["gross_value"] for row in r["simulation"]["nav"]]
        net_growth *= 1.0 + m.cumulative_return([init, *nav])
        gross_growth *= 1.0 + m.cumulative_return([init, *gross])
        session_rets += m.period_returns(nav)
        path = [init, *nav]
        for k in range(1, len(path)):
            chained.append(chained[-1] * path[k] / path[k - 1])
        for k in sums:
            sums[k] += float(r["metrics"].get(k) or 0.0)
    n = len(session_rets)
    mean = sum(session_rets) / n if n else 0.0
    sd = math.sqrt(sum((x - mean) ** 2 for x in session_rets) / (n - 1)) if n > 1 else 0.0
    rf_period = (1.0 + cash_rate_annual) ** (1.0 / periods_per_year) - 1.0
    return {
        "net_cumulative_return": net_growth - 1.0,
        "gross_cumulative_return": gross_growth - 1.0,
        "annualized_volatility": sd * math.sqrt(periods_per_year),
        "sharpe_ratio": None if sd == 0 else (mean - rf_period) / sd * math.sqrt(periods_per_year),
        "max_drawdown": m.max_drawdown(chained),
        **sums,
    }


def _seed_label(seed: int | None) -> str | None:
    return None if seed is None else f"seed-{seed}"


# ===================================================================== report
def build_report(
    run: BenchmarkRun | Mapping[str, Any],
    *,
    cost_records: Iterable[Mapping[str, Any]] = (),
    config: ReportConfig | Mapping[str, Any] | None = None,
    holdout_access: Mapping[str, Any] | None = None,
    accuracy: Mapping[str, Mapping[str, Any]] | None = None,
    training_rewards: Mapping[str, Mapping[str, Any]] | None = None,
    narrative: Sequence[str] = (),
    bias_section: Mapping[str, Any] | None = None,
) -> BenchmarkReport:
    """``bias_section`` (:func:`finplan_model.jobs.universe.bias_section`) is mandatory for an
    ``equity-etf-daily`` dataset: the report then carries "Hindsight and survivorship bias" with the
    snapshot's disclosures unchanged and the cash assumption (part of the checksummed content)."""
    doc = run.to_dict() if isinstance(run, BenchmarkRun) else dict(run)
    dataset_id = str((doc.get("dataset") or {}).get("dataset_id") or "")
    if "/equity-etf-daily/" in f"{dataset_id}/" and not (bias_section and bias_section.get("bias_disclosures")):
        raise FinplanError.validation("a universe report must carry the snapshot's bias disclosures", pointer="/bias_disclosures", reason="bias_disclosures_missing")
    cfg = config if isinstance(config, ReportConfig) else ReportConfig.from_dict(config)
    entries = [ResultEntry.from_dict(e) for e in doc["entries"]]
    if not entries:
        raise FinplanError.validation("a report needs at least one stored result", pointer="/entries")
    synthetic = all(bool(e.result["synthetic"]) for e in entries)
    descriptors: dict[str, dict[str, Any]] = doc["descriptors"]
    sim_cfg = doc["simulation_configuration"]
    risk_free = {"source": "configured_cash_rate", "cash_rate_annual": sim_cfg["cash_rate_annual"]}

    # ---- portfolio performance (rows per strategy x period, grouped by period type)
    periods: dict[str, list[dict[str, Any]]] = {p: [] for p in PERIOD_TYPES}
    for e in sorted(entries, key=lambda e: (PERIOD_TYPES.index(e.period_type), e.period_id, e.strategy, -1 if e.seed is None else e.seed)):
        r = e.result
        if r["metrics"].get("sharpe_risk_free_source") not in (None, "configured_cash_rate"):
            risk_free = {"source": r["metrics"]["sharpe_risk_free_source"], "cash_rate_annual": sim_cfg["cash_rate_annual"]}
        periods[e.period_type].append(
            {
                "strategy": e.strategy,
                "seed": e.seed,
                "period_type": e.period_type,
                "period_id": e.period_id,
                "start": r["evaluation_window"]["start"],
                "end": r["evaluation_window"]["end"],
                "synthetic": bool(r["synthetic"]),
                "solution_status": r["solution_status"],
                "metrics": _portfolio(r["metrics"]),
                "result_checksum": r["result_checksum"],
                **({"result_ref": e.result_ref} if e.result_ref else {}),
            }
        )
    # aggregate of walk-forward folds per (strategy, seed)
    groups: dict[tuple[str, int | None], list[ResultEntry]] = {}
    for e in entries:
        if e.period_type == "walk_forward_fold":
            groups.setdefault((e.strategy, e.seed), []).append(e)
    for (label, seed), es in sorted(groups.items(), key=lambda kv: (kv[0][0], -1 if kv[0][1] is None else kv[0][1])):
        es = sorted(es, key=lambda x: x.period_id)
        periods["walk_forward_fold"].append(
            {
                "strategy": label,
                "seed": seed,
                "period_type": "walk_forward_fold",
                "period_id": "aggregate",
                "aggregation": "stitched_out_of_sample",
                "folds": len(es),
                "start": es[0].result["evaluation_window"]["start"],
                "end": es[-1].result["evaluation_window"]["end"],
                "synthetic": all(bool(x.result["synthetic"]) for x in es),
                "metrics": aggregate_fold_metrics([x.result for x in es], periods_per_year=int(sim_cfg["periods_per_year"]), cash_rate_annual=float(sim_cfg["cash_rate_annual"])),
            }
        )
    # holdout column values come from the holdout metrics records (same numbers by construction)
    records = list(doc.get("holdout_records") or [])
    rec_by_key = {(r.get("strategy_label", r["strategy"]), r.get("seed")): r for r in records}
    for row in periods["holdout"]:
        rec = rec_by_key.get((row["strategy"], row["seed"]))
        if rec is None:
            raise FinplanError.validation("a holdout result has no holdout metrics record", pointer="/holdout_records", strategy=row["strategy"])
        if rec["net_cumulative_return"] != row["metrics"]["net_cumulative_return"] or rec["max_drawdown"] != row["metrics"]["max_drawdown"]:
            raise FinplanError.internal("holdout metrics record differs from the evaluated holdout result", strategy=row["strategy"])
        row["holdout_record"] = {"result_checksum": rec["result_checksum"], "net_cumulative_return": rec["net_cumulative_return"], "max_drawdown": rec["max_drawdown"]}
    if not cfg.include_seed_rows:
        for p in PERIOD_TYPES:
            periods[p] = [r for r in periods[p] if r["seed"] is None]

    # ---- variability (strategies with randomness)
    variability: dict[str, Any] = {}
    for label, d in sorted(descriptors.items()):
        if not d.get("has_randomness"):
            continue
        per: dict[str, Any] = {}
        for p in PERIOD_TYPES:
            rows = [r for r in periods[p] if r["strategy"] == label]
            for pid in sorted({r["period_id"] for r in rows}):
                pr = [r for r in rows if r["period_id"] == pid]
                stats: dict[str, Any] = {}
                for k in PORTFOLIO_METRICS:
                    vals = [r["metrics"][k] for r in pr if isinstance(r["metrics"].get(k), (int, float))]
                    if vals:
                        mean = sum(vals) / len(vals)
                        stats[k] = {"mean": mean, "min": min(vals), "max": max(vals), "range": max(vals) - min(vals)}
                per[f"{p}:{pid}"] = {"period_type": p, "period_id": pid, "n_seeds": len(pr), "seeds": sorted(r["seed"] for r in pr if r["seed"] is not None), "metrics": stats}
        variability[label] = {"n_seeds": len({e.seed for e in entries if e.strategy == label}), "periods": per}

    # ---- model accuracy / training rewards (never mixed with portfolio metrics)
    def _section(name: str, provided: Mapping[str, Mapping[str, Any]] | None, applies: Any) -> dict[str, Any]:
        provided = dict(provided or {})
        rows: list[dict[str, Any]] = []
        status: dict[str, str] = {}
        for label, d in sorted(descriptors.items()):
            if not applies(d):
                status[label] = "not_applicable"
                if label in provided:
                    raise FinplanError.validation(f"{name} given for a strategy it does not apply to", pointer=f"/{name}/{label}")
                continue
            if label not in provided:
                status[label] = "missing"
                continue
            status[label] = "filled"
            for period_key, values in sorted(provided[label].items()):
                clash = sorted(set(values) & set(PORTFOLIO_METRICS))
                if clash or any(any(w in str(k).lower() for w in _BLEND_WORDS) for k in values):
                    raise FinplanError.validation(f"{name} metrics must not reuse portfolio metric names or blend sections", pointer=f"/{name}/{label}/{period_key}", metrics=clash)
                rows.append({"strategy": label, "period": period_key, "synthetic": synthetic, "metrics": dict(sorted(values.items()))})
        filled = any(v == "filled" for v in status.values())
        return {"status": "filled" if filled else "not_applicable", "by_strategy": status, "rows": rows}

    accuracy_section = _section("model_accuracy", accuracy, lambda d: bool(d.get("makes_predictions")))
    rewards_section = _section("training_rewards", training_rewards, lambda d: d.get("family") == "learned")

    # ---- compute cost
    cost_rows = []
    for n, c in enumerate(sorted((dict(c) for c in cost_records), key=lambda c: str(c.get("run_id")))):
        p = f"/cost_records/{n}"
        require_id("run_id", c.get("run_id"))
        for k in ("instance_type", "instance_count", "estimated_usd"):
            if c.get(k) is None:
                raise FinplanError.validation(f"cost record lacks {k}", pointer=f"{p}/{k}")
        actual = c.get("actual_usd")
        cost_rows.append(
            {
                "run_id": c["run_id"],
                "instance_type": c["instance_type"],
                "instance_count": int(c["instance_count"]),
                "billed_runtime_seconds": c.get("billed_runtime_seconds"),
                "estimated_cost": {"usd": float(c["estimated_usd"]), "label": "estimated", "source": "pre_flight_estimate"},
                "actual_cost": {"status": "pending", "label": "actual"} if actual is None else {"status": "available", "label": "actual", "usd": float(actual)},
                "synthetic_inputs": synthetic,
            }
        )
    cost_section = {"status": "filled" if cost_rows else "not_recorded", "rows": cost_rows}

    # ---- holdout block (access log attached whenever holdout results are reported)
    holdout_block: dict[str, Any] | None = None
    if periods["holdout"]:
        if holdout_access is None:
            raise FinplanError.validation("a report with holdout results must attach the holdout access log", pointer="/holdout_access")
        holdout_block = {
            "bounds": doc.get("holdout_bounds"),
            "access_log": [{k: a.get(k) for k in ("run_id", "model_version", "family", "purpose", "outcome", "at")} for a in holdout_access.get("accesses", [])],
            "refused_attempts": len(holdout_access.get("refused_attempts", [])),
            "evaluations_by_family": dict(holdout_access.get("evaluations_by_family", {})),
            "reused": bool(holdout_access.get("reused")),
            "reused_families": list(holdout_access.get("reused_families", [])),
            "records": [{k: r[k] for k in ("strategy", "seed", "dataset_id", "holdout", "simulation_configuration_id", "cost_model_id", "evaluator_version", "net_cumulative_return", "max_drawdown", "result_checksum")} for r in records],
            "record_refs": list(doc.get("holdout_record_refs") or []),
        }

    content = {
        "report_version": REPORT_VERSION,
        "title": cfg.title,
        "synthetic": synthetic,
        "run_id": doc.get("run_id"),
        "dataset": doc["dataset"],
        "evaluator": {k: doc["identity"][k] for k in ("evaluator_version", "image_digest", "simulation_configuration_id", "cost_model_id")},
        "simulation_configuration": sim_cfg,
        "strategies": [{**descriptors[label], "label": label} for label in sorted(descriptors)],
        "auto_added_controls": list(doc["request"].get("auto_added_controls", [])),
        "folds": [{"fold_id": f["fold_id"], "train": f["train"], "test": f["test"], "embargo_sessions": f["embargo_sessions"]} for f in doc.get("folds") or []],
        "sections": {
            "portfolio_performance": {"status": "filled", "risk_free": risk_free, "metrics": list(PORTFOLIO_METRICS), "periods": {p: rows for p, rows in periods.items() if rows}},
            "model_accuracy": accuracy_section,
            "training_rewards": rewards_section,
            "compute_cost": cost_section,
        },
        "variability": variability,
        "holdout": holdout_block,
        "period_labels": [p for p in PERIOD_TYPES if periods[p]],
    }
    if bias_section:
        content["bias"] = {"title": "Hindsight and survivorship bias", **{k: v for k, v in dict(bias_section).items() if k != "title"}}
    content = _normalized(content)
    assert_aggregate_only(content)
    _validate_sections(content)
    return BenchmarkReport(content, sha256_checksum(canonical_json_bytes(content)), tuple(narrative))


def _normalized(doc: Any) -> Any:
    """JSON round trip through the canonical form (floats as canonical numbers, no tuples)."""
    import json

    return json.loads(canonical_json_bytes(doc))


def _validate_sections(content: Mapping[str, Any]) -> None:
    sections = content["sections"]
    if set(sections) != set(SECTIONS):
        raise FinplanError.validation("report sections must be exactly portfolio_performance, model_accuracy, training_rewards and compute_cost", pointer="/sections")
    for p, rows in sections["portfolio_performance"]["periods"].items():
        for r in rows:
            if set(r["metrics"]) - set(PORTFOLIO_METRICS):
                raise FinplanError.validation("portfolio rows carry only portfolio metrics", pointer=f"/sections/portfolio_performance/periods/{p}")
            if r["period_type"] not in PERIOD_TYPES or "synthetic" not in r:
                raise FinplanError.validation("every reported number is labeled with its period type and synthetic flag", pointer=f"/sections/portfolio_performance/periods/{p}")


def report_from_stored(run_ref: ArtifactRef | Mapping[str, Any], store: ArtifactStore, **kwargs: Any) -> BenchmarkReport:
    """Regenerate a report from a stored benchmark run document (REP-06)."""
    return build_report(store.get_json(run_ref), **kwargs)  # type: ignore[attr-defined]


def store_report(report: BenchmarkReport, store: ArtifactStore) -> dict[str, Any]:
    """Store the numeric report (and, separately, its narrative) in research storage."""
    require_research_storage(store, synthetic=report.synthetic)
    assert_aggregate_only(report.content)
    ref = store.put_json(report.to_dict(), kind=REPORT_KIND, synthetic=True if report.synthetic else None, domain="finance")  # type: ignore[attr-defined]
    out = {"report_ref": ref.to_dict(), "report_checksum": report.report_checksum}
    if report.narrative:
        nref = store.put_json({"report_checksum": report.report_checksum, "narrative": list(report.narrative), "synthetic": report.synthetic}, kind=NARRATIVE_KIND, synthetic=True if report.synthetic else None, domain="finance")  # type: ignore[attr-defined]
        out["narrative_ref"] = nref.to_dict()
    return out


def to_run_result_payload(report: BenchmarkReport, strategy: str, *, period: str = "walk_forward_fold", period_id: str = "aggregate") -> dict[str, Any]:
    """The contract ``finance/v1/run-result-payload`` sections for one strategy (job results).

    ``performance`` holds the strategy's portfolio metrics of one report row, ``accuracy`` its
    accuracy metrics (empty for non-predictive strategies) and ``compute_cost`` the first cost row.
    """
    candidates = [r for r in report.content["sections"]["portfolio_performance"]["periods"].get(period, []) if r["strategy"] == strategy and r["period_id"] == period_id]
    rows = sorted(candidates, key=lambda r: -1 if r["seed"] is None else r["seed"])[:1]
    if not rows:
        raise FinplanError.validation("no report row for that strategy and period", pointer="/strategy")
    perf = {k: float(v) for k, v in rows[0]["metrics"].items() if isinstance(v, (int, float))}
    acc = {}
    for r in report.content["sections"]["model_accuracy"]["rows"]:
        if r["strategy"] == strategy:
            acc.update({k: float(v) for k, v in r["metrics"].items() if isinstance(v, (int, float))})
    cost: dict[str, Any] = {}
    crow = report.content["sections"]["compute_cost"]["rows"]
    if crow:
        cost["estimated_usd"] = crow[0]["estimated_cost"]["usd"]
        if crow[0]["actual_cost"].get("usd") is not None:
            cost["actual_usd"] = crow[0]["actual_cost"]["usd"]
        if crow[0].get("billed_runtime_seconds") is not None:
            cost["instance_seconds"] = float(crow[0]["billed_runtime_seconds"]) * int(crow[0]["instance_count"])
    out: dict[str, Any] = {"performance": perf, "accuracy": acc, "compute_cost": cost}
    if report.synthetic:
        out["synthetic"] = True
    return out
